export type MembershipRole = "Admin" | "Lead" | "Member" | "Host";

export interface MembershipItem {
  id: string;
  name: string;
  slug: string;
  tagline?: string;
  isPrivate: boolean;
  role: MembershipRole;
  initials: string;
  color: string;
  type: "space" | "subspace";
  parentId?: string;
  parentName?: string;
  image?: string;
  // Enhanced dashboard fields
  isPinned?: boolean;
  pinnedAt?: Date;
  lastModified?: Date;
  lastActivityDate?: Date;
  activityScore?: number;
  createdAt?: Date;
}

const colors = [
  "#1d384a",
  "#2563eb",
  "#7c3aed",
  "#059669",
  "#d97706",
  "#db2777",
];

const c = (i: number) => colors[i % colors.length];

export const MOCK_MEMBERSHIPS: MembershipItem[] = [
  {
    id: "welcome",
    type: "space",
    name: "Welcome",
    slug: "welcome",
    tagline: "Get started with your first space and learn the basics.",
    isPrivate: false,
    role: "Member",
    initials: "W",
    color: "#2563eb",
    image: "https://picsum.photos/1200/256?random=welcome",
    isPinned: false,
    lastModified: new Date("2026-07-07"),
    lastActivityDate: new Date("2026-07-07"),
    activityScore: 100,
    createdAt: new Date("2026-07-07"),
  },
  {
    id: "s1",
    type: "space",
    name: "Innovation Lab",
    slug: "innovation-lab",
    tagline: "Central hub for innovation initiatives and rapid experiments.",
    isPrivate: true,
    role: "Lead",
    initials: "IL",
    color: c(0),
    image: "https://picsum.photos/1200/256?random=1",
    isPinned: true,
    pinnedAt: new Date("2026-06-20"),
    lastModified: new Date("2026-07-05"),
    lastActivityDate: new Date("2026-07-04"),
    activityScore: 85,
    createdAt: new Date("2026-01-15"),
  },
  {
    id: "s1-sub-1",
    type: "subspace",
    parentId: "s1",
    parentName: "Innovation Lab",
    name: "Q1 Experiments",
    slug: "q1-experiments",
    isPrivate: true,
    role: "Lead",
    initials: "Q1",
    color: c(0),
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s1-sub-2",
    type: "subspace",
    parentId: "s1",
    parentName: "Innovation Lab",
    name: "Idea Repository",
    slug: "idea-repository",
    isPrivate: false,
    role: "Member",
    initials: "IR",
    color: c(0),
    image: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s2",
    type: "space",
    name: "Design Workshop",
    slug: "design-workshop",
    tagline: "Design critiques, assets, and product exploration.",
    isPrivate: false,
    role: "Admin",
    initials: "DW",
    color: c(1),
    image: "https://images.unsplash.com/photo-1735639013995-086e648eaa38?auto=format&fit=crop&q=80&w=1200",
    isPinned: false,
    lastModified: new Date("2026-07-03"),
    lastActivityDate: new Date("2026-07-02"),
    activityScore: 62,
    createdAt: new Date("2026-02-10"),
  },
  {
    id: "s3",
    type: "space",
    name: "Team Sync",
    slug: "team-sync",
    tagline: "Weekly alignment and delivery planning for the core team.",
    isPrivate: true,
    role: "Member",
    initials: "TS",
    color: c(2),
    image: "https://images.unsplash.com/photo-1768659347532-74d3b1efb0ae?auto=format&fit=crop&q=80&w=1200",
    isPinned: true,
    pinnedAt: new Date("2026-06-25"),
    lastModified: new Date("2026-07-01"),
    lastActivityDate: new Date("2026-06-30"),
    activityScore: 45,
    createdAt: new Date("2026-03-05"),
  },
  {
    id: "s3-sub-1",
    type: "subspace",
    parentId: "s3",
    parentName: "Team Sync",
    name: "Daily Standup",
    slug: "daily-standup",
    isPrivate: true,
    role: "Member",
    initials: "DS",
    color: c(2),
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s4",
    type: "space",
    name: "Future Strategy",
    slug: "future-strategy",
    tagline: "Long-range planning and roadmap discussions.",
    isPrivate: false,
    role: "Host",
    initials: "FS",
    color: c(3),
    image: "https://images.unsplash.com/photo-1676276376052-dc9c9c0b6917?auto=format&fit=crop&q=80&w=1200",
    isPinned: false,
    lastModified: new Date("2026-06-28"),
    lastActivityDate: new Date("2026-06-27"),
    activityScore: 78,
    createdAt: new Date("2025-12-01"),
  },
  {
    id: "s4-sub-1",
    type: "subspace",
    parentId: "s4",
    parentName: "Future Strategy",
    name: "Market Research",
    slug: "market-research",
    isPrivate: false,
    role: "Member",
    initials: "MR",
    color: c(3),
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s4-sub-2",
    type: "subspace",
    parentId: "s4",
    parentName: "Future Strategy",
    name: "2026 Roadmap",
    slug: "2026-roadmap",
    isPrivate: false,
    role: "Member",
    initials: "26",
    color: c(3),
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s4-sub-3",
    type: "subspace",
    parentId: "s4",
    parentName: "Future Strategy",
    name: "Competitor Analysis",
    slug: "competitor-analysis",
    isPrivate: true,
    role: "Lead",
    initials: "CA",
    color: c(3),
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s4-sub-4",
    type: "subspace",
    parentId: "s4",
    parentName: "Future Strategy",
    name: "Investment Planning",
    slug: "investment-planning",
    isPrivate: false,
    role: "Member",
    initials: "IP",
    color: c(3),
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s4-sub-5",
    type: "subspace",
    parentId: "s4",
    parentName: "Future Strategy",
    name: "Partnership Outreach",
    slug: "partnership-outreach",
    isPrivate: false,
    role: "Member",
    initials: "PO",
    color: c(3),
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s4-sub-6",
    type: "subspace",
    parentId: "s4",
    parentName: "Future Strategy",
    name: "Technology Scouting",
    slug: "technology-scouting",
    isPrivate: true,
    role: "Member",
    initials: "TS",
    color: c(3),
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200",
  },
  {
    id: "s5",
    type: "space",
    name: "Community Events",
    slug: "community-events",
    tagline: "Planning meetups, webinars, and community activity.",
    isPrivate: true,
    role: "Lead",
    initials: "CE",
    color: c(4),
    image: "https://images.unsplash.com/photo-1768776179834-93e6cafc6d97?auto=format&fit=crop&q=80&w=1200",
    isPinned: true,
    pinnedAt: new Date("2026-06-10"),
    lastModified: new Date("2026-06-29"),
    lastActivityDate: new Date("2026-06-29"),
    activityScore: 92,
    createdAt: new Date("2025-10-20"),
  },
  {
    id: "s6",
    type: "space",
    name: "Platform Management",
    slug: "platform-management",
    tagline: "Templates, governance, and platform operations.",
    isPrivate: true,
    role: "Admin",
    initials: "PM",
    color: c(5),
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200",
    isPinned: false,
    lastModified: new Date("2026-06-15"),
    lastActivityDate: new Date("2026-06-14"),
    activityScore: 35,
    createdAt: new Date("2025-09-01"),
  },
  // Additional spaces to fill all 5 rows
  {
    id: "s7",
    type: "space",
    name: "Research & Development",
    slug: "research-development",
    tagline: "Deep research and emerging technologies exploration.",
    isPrivate: false,
    role: "Lead",
    initials: "RD",
    color: c(0),
    image: "https://picsum.photos/1200/256?random=7",
    isPinned: false,
    lastModified: new Date("2026-05-20"),
    lastActivityDate: new Date("2026-05-19"),
    activityScore: 28,
    createdAt: new Date("2025-08-10"),
  },
  {
    id: "s8",
    type: "space",
    name: "Quality Assurance",
    slug: "quality-assurance",
    tagline: "Testing, QA processes, and bug tracking.",
    isPrivate: false,
    role: "Admin",
    initials: "QA",
    color: c(1),
    image: "https://picsum.photos/1200/256?random=8",
    isPinned: false,
    lastModified: new Date("2026-05-10"),
    lastActivityDate: new Date("2026-05-09"),
    activityScore: 52,
    createdAt: new Date("2025-07-15"),
  },
  {
    id: "s9",
    type: "space",
    name: "Operations Hub",
    slug: "operations-hub",
    tagline: "Daily operations, processes, and workflows.",
    isPrivate: true,
    role: "Host",
    initials: "OH",
    color: c(2),
    image: "https://picsum.photos/1200/256?random=9",
    isPinned: false,
    lastModified: new Date("2026-04-30"),
    lastActivityDate: new Date("2026-04-29"),
    activityScore: 15,
    createdAt: new Date("2025-06-01"),
  },
  {
    id: "s10",
    type: "space",
    name: "Marketing & Communications",
    slug: "marketing-communications",
    tagline: "Brand, campaigns, and content strategy.",
    isPrivate: false,
    role: "Host",
    initials: "MC",
    color: c(3),
    image: "https://picsum.photos/1200/256?random=10",
    isPinned: false,
    lastModified: new Date("2026-07-04"),
    lastActivityDate: new Date("2026-07-04"),
    activityScore: 88,
    createdAt: new Date("2025-05-10"),
  },
  {
    id: "s11",
    type: "space",
    name: "Customer Success",
    slug: "customer-success",
    tagline: "Customer support, feedback, and success stories.",
    isPrivate: false,
    role: "Member",
    initials: "CS",
    color: c(4),
    image: "https://picsum.photos/1200/256?random=11",
    isPinned: false,
    lastModified: new Date("2026-04-15"),
    lastActivityDate: new Date("2026-07-02"),
    activityScore: 76,
    createdAt: new Date("2025-04-01"),
  },
  {
    id: "s12",
    type: "space",
    name: "Data Analytics",
    slug: "data-analytics",
    tagline: "Analytics, dashboards, and insights.",
    isPrivate: false,
    role: "Lead",
    initials: "DA",
    color: c(0),
    image: "https://picsum.photos/1200/256?random=12",
    isPinned: false,
    lastModified: new Date("2026-03-20"),
    lastActivityDate: new Date("2026-03-19"),
    activityScore: 42,
    createdAt: new Date("2025-03-15"),
  },
  {
    id: "s13",
    type: "space",
    name: "Security & Compliance",
    slug: "security-compliance",
    tagline: "Security protocols and compliance standards.",
    isPrivate: true,
    role: "Admin",
    initials: "SC",
    color: c(1),
    image: "https://picsum.photos/1200/256?random=13",
    isPinned: false,
    lastModified: new Date("2026-02-10"),
    lastActivityDate: new Date("2026-02-09"),
    activityScore: 33,
    createdAt: new Date("2025-02-01"),
  },
  {
    id: "s14",
    type: "space",
    name: "Product Development",
    slug: "product-development",
    tagline: "Product roadmap and feature planning.",
    isPrivate: false,
    role: "Lead",
    initials: "PD",
    color: c(2),
    image: "https://picsum.photos/1200/256?random=14",
    isPinned: false,
    lastModified: new Date("2026-01-15"),
    lastActivityDate: new Date("2026-01-14"),
    activityScore: 55,
    createdAt: new Date("2024-12-20"),
  },
  {
    id: "s15",
    type: "space",
    name: "Finance & Budgeting",
    slug: "finance-budgeting",
    tagline: "Financial planning and budget management.",
    isPrivate: true,
    role: "Admin",
    initials: "FB",
    color: c(3),
    image: "https://picsum.photos/1200/256?random=15",
    isPinned: false,
    lastModified: new Date("2025-12-05"),
    lastActivityDate: new Date("2025-12-04"),
    activityScore: 38,
    createdAt: new Date("2024-11-10"),
  },
  {
    id: "s16",
    type: "space",
    name: "Human Resources",
    slug: "human-resources",
    tagline: "HR policies, hiring, and team culture.",
    isPrivate: true,
    role: "Host",
    initials: "HR",
    color: c(4),
    image: "https://picsum.photos/1200/256?random=16",
    isPinned: false,
    lastModified: new Date("2025-11-20"),
    lastActivityDate: new Date("2026-07-01"),
    activityScore: 71,
    createdAt: new Date("2024-10-05"),
  },
  {
    id: "s17",
    type: "space",
    name: "Infrastructure & DevOps",
    slug: "infrastructure-devops",
    tagline: "Cloud infrastructure and deployment pipelines.",
    isPrivate: true,
    role: "Host",
    initials: "ID",
    color: c(5),
    image: "https://picsum.photos/1200/256?random=17",
    isPinned: false,
    lastModified: new Date("2025-10-10"),
    lastActivityDate: new Date("2026-06-28"),
    activityScore: 68,
    createdAt: new Date("2024-09-01"),
  },
  {
    id: "s18",
    type: "space",
    name: "Learning & Development",
    slug: "learning-development",
    tagline: "Training programs and skill development.",
    isPrivate: false,
    role: "Lead",
    initials: "LD",
    color: c(0),
    image: "https://picsum.photos/1200/256?random=18",
    isPinned: false,
    lastModified: new Date("2025-09-15"),
    lastActivityDate: new Date("2026-06-25"),
    activityScore: 82,
    createdAt: new Date("2024-08-20"),
  },
  {
    id: "s19",
    type: "space",
    name: "Sustainability Initiatives",
    slug: "sustainability-initiatives",
    tagline: "Green initiatives and sustainability goals.",
    isPrivate: false,
    role: "Host",
    initials: "SI",
    color: c(1),
    image: "https://picsum.photos/1200/256?random=19",
    isPinned: false,
    lastModified: new Date("2025-08-25"),
    lastActivityDate: new Date("2026-06-20"),
    activityScore: 64,
    createdAt: new Date("2024-07-12"),
  },
];
